### ISSUE TITLE
Add Support for a church organ

### ISSUE THREAD

**Issue by YevsVZ** [LenweSaralonde/MusicianExtended#1]
Hello for holy light church role-play we could use a Church Organ, it would be really lovely if you could implement this.

**Comment by LenweSaralonde** [comment]
That's a great idea, but it will probably end up in a plugin, not the main add-on.

**Comment by LenweSaralonde** [comment]
https://www.youtube.com/watch?v=d6BhKFS9iNo

Samplephonics Leeds Town Hall Organ, preset 5 is dope.
https://www.samplephonics.com/products/free/sampler-instruments/the-leeds-town-hall-organ#

**Comment by LenweSaralonde** [comment]
A new plugin has been created to add more instruments : https://github.com/LenweSaralonde/MusicianExtended

The pipe organ is the first added instrument. 5d98783050d7adba23cc4b7b8cfd5a1d243e1b33
